config/routes.rb
Rails.application.routes.draw do

  root 'users#sign_in'
  get 'users/dashboard_page'

  namespace :admin do
    resources :dashboard, only: [] do
      get :dashboard_page, on: :collection
    end
    resources :users
    resources :companies
    resources :records
    resources :company_histories, only: [:show]
    resources :services
    resources :processes
  end

  namespace :users do
    get :password_new
    post :generate_new_password_email
    resources :companies, only: [:index, :show] do
      get :change_year, on: :collection
    end
    resources :company_histories, only: [:update, :create, :new]
    resources :records, only: [:edit, :update, :create, :new] do
      get :download_pdf, on: :member
      get :record_pdf, on: :member
      get :download, on: :member
      patch :update_log, on: :collection
    end
  end

  devise_for :users, path: 'admins', :controllers => { :invitations => 'invitations', :sessions => 'sessions', :passwords => 'passwords'}

  # devise_for :admins , path: 'admins', :controllers => { :invitations => 'invitations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  #association
  attr_accessor :user_ids

  has_many :company_users
  has_many :users, through: :company_users, dependent: :destroy
  has_many :records, dependent: :destroy
  belongs_to :created_by, class_name: 'Company', foreign_key: 'parent_id', optional: true
  has_many :created_companies, class_name: 'Company', foreign_key: 'parent_id'
  has_many :company_histories, dependent: :destroy
  enum cmp_size: [:small, :large]

  #includes
  has_attached_file :company_logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :company_logo, content_type: ['image/jpeg', 'image/jpg', 'image/png']

  validates :cmp_name, presence: true
  validates :industry, presence: true
  validates :sub_industry, presence: true
  validates :user_ids, presence: true
  validates :parent_id, presence: true, if: -> {self.is_holding == true}
  validates_uniqueness_of :cmp_name

  def child_companies
    self.created_companies
  end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /admin/companies
  # GET /admin/companies.json
  def index
    @companies = Company.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /admin/companies/1
  # GET /admin/companies/1.json
  def show
    @company_histories = @company.company_histories
  end

  # GET /admin/companies/new
  def new
    @company = Company.new
  end

  # GET /admin/companies/1/edit
  def edit
  end

  # POST /admin/companies
  # POST /admin/companies.json
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      # @company.company_histories.build(user_id: params[:company][:user_id], year: Time.now().strftime("%Y"))
      if @company.save
        @company.users << User.where(id: params[:company][:user_ids])
        format.html { redirect_to admin_company_path(@company), notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/companies/1
  # PATCH/PUT /admin/companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        @company.users << User.where(id: params[:company][:user_ids])
        format.html { redirect_to admin_company_path(@company), notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/companies/1
  # DELETE /admin/companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:cmp_name, :industry, :sub_industry, :is_holding, :parent_id, :company_logo, user_ids: [] )
    end
end

app/controllers/users/companies_controller.rb
class Users::CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :get_companies
  before_action :set_company, only: [:show, :change_year]
  before_action :user_side


  def user_side
    if current_user.role == "Admin"
      redirect_to dashboard_page_admin_dashboard_index_path
    end
  end


  def index
    if current_user.role == 'Consultant'
      # @companies = @companies.where(user_id: current_user.id)
      @companies = @companies.includes(:users).where('users.id = ?', current_user.id).references(:users)

    end
    @companies = @companies.paginate(:page => params[:page], :per_page => 8)
  end

  def show
    if flash['year'].present?
      @working_year = flash['year']
    else
      @working_year = Time.now().strftime("%Y")
    end

    if current_user.role == "Consultant"
      @company_histories = @company_histories.where(user_id: current_user.id)
      @records = @records.where(user_id: current_user.id)
    end

    if !@company_histories.present?
      @company_history = CompanyHistory.create(user_id: current_user.id, company_id: @company.id, year: Time.now().strftime("%Y"))
      @company_histories = CompanyHistory.where(company_id: @company.id)
    end

    @company_histories_years = @company_histories.order(:year).pluck(:year)
    @records_years = @records.where.not(date_of_service_provided: nil).all.order("date_of_service_provided").map {|d| d.date_of_service_provided.strftime("%Y").to_i }.uniq
    if @records_years.any?
      @years = (@records_years + @company_histories_years).uniq.sort
    else
      @years = (@company_histories_years).uniq.sort
    end

    @current_company_history = @company_histories.find_by(year: @working_year)
  end

  def change_year
    if current_user.role == 'Consultant'
      @company_histories = @company_histories.where(user_id: current_user.id)
    end
    @current_company_history = @company_histories.find_by(year: params[:year])

    if !@current_company_history.present?
      @current_company_history = CompanyHistory.create!(user_id: @company.user_id, company_id: @company.id, year: params[:year])
    end

    respond_to do |format|
      format.js
    end
  end

  protected

  def set_company
    @company = Company.find(params[:id])
    @company_histories = @company.company_histories
    @records = @company.records.order("date_of_service_provided")
  end

  def get_companies
    @companies = Company.all
  end

end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/users/companies_helper.rb
module Users::CompaniesHelper
end

app/views/admin/companies/_form.html.erb
<%= form_for company, method: method, url: path do |form| %>
  <div class="box-body">
    <div class="form-group field col-lg-7">
      <%= form.label :cmp_name, "Company Name" %>
      <%= form.text_field :cmp_name, class: 'form-control', placeholder: "Enter company name" %>
      <p class='error'><%= show_errors(company, :cmp_name, "Company Name") %></p>
    </div>

    <div class="form-group field col-lg-7">
      <%= label_tag :user_ids, "Select the users" %>
      <%= select_tag("company[user_ids][]", options_for_select(User.all.map {|s| [s.first_name, s.id]}, company.users.ids), {class: 'form-control select2 select2-hidden-accessible', multiple: :true})  %>
      <p class='error'><%= show_errors(company, :user_ids, "Users") %></p>
    </div>

    <div class="form-group field col-lg-7">
      <%= form.label :is_holding %>
      <%= form.check_box :is_holding, id: 'is_holding' %>
    </div>

    <div class="form-group field col-lg-7 company-class">
      <%= form.label :parent_id, "Select Parent Company" %>
      <%= form.select :parent_id, Company.all.collect { |r| [ r.cmp_name.capitalize, r.id ] },{include_blank: "Select Company"}, { class: 'form-control select2 company_class_select', style: "width: 100%;"}   %>
      <p class='error'><%= show_errors(company, :parent_id, "Parent company") %></p>
    </div>

    <div class="form-group field col-lg-7">
      <%= form.label :industry %>
      <%= form.text_field :industry, class: 'form-control', placeholder: "Enter industry" %>
      <p class='error'><%= show_errors(company, :industry, "Industry") %></p>
    </div>

    <div class="form-group field col-lg-7">
      <%= form.label :sub_industry %>
      <%= form.text_field :sub_industry, class: 'form-control', placeholder: "Enter sub industry" %>
      <p class='error'><%= show_errors(company, :sub_industry, "Sub Industry") %></p>
    </div>

    <div class="form-group field col-lg-7">
      <%= form.label :company_logo %>
      <%= form.file_field :company_logo %>
      <p class='error'><%= show_errors(company, :company_logo, "Company logo") %></p>
    </div>

</div>

<div class="box-footer">
  <%= form.submit "Submit", class: "btn btn-primary" %>
    <% if @company.new_record? %>
      <%= link_to 'Back', admin_companies_path, class: "btn btn-primary" %>
    <%else%>
      <%= link_to 'Show', admin_company_path(@company) , class: "btn btn-primary" %>
      <%= link_to 'Back', admin_companies_path, class: "btn btn-primary" %>
    <%end%>
  <% end %>
</div>


<script type="text/javascript">
   $(document).on('turbolinks:load', function() {
    if ($('#is_holding').is(":checked")){
      $(".company-class").show();
    }
    else {
      $(".company-class").hide();
    }
    $('#is_holding').change(function() {
        if(this.checked){
          $(".company-class").show();
        }
        else{
          $('.company_class_select').val('');
          $(".company-class").hide();
        }
    });
  });
</script>

app/views/admin/companies/edit.html.erb
<% content_for :companies_class, "active"%>
<section class="content-header">
  <h1>
    Edit Company
    <small>Preview</small>
  </h1>
</section>
<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Update Company</h3>
        </div>
        <%= render 'form', company: @company, method: 'patch', path: admin_company_path %>
      </div>
    </div>
  </div>
</section>

app/views/admin/companies/index.html.erb
<% content_for :companies_class, "active"%>
<p id="notice"><%= notice %></p>
<section class="content-header">
  <h1>
    Companies
    <!-- <small>advanced tables</small> -->
  </h1>
  <ol class="breadcrumb">
    <%= link_to 'New Company', new_admin_company_path, class: "btn btn-block btn-primary" %>
  </ol>
</section>


<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Companies Data</h3>
        </div>
        <div class="box-body overflow-y">
          <table id="example3" class="table table-bordered table-hover">
            <thead>
            <tr>
              <th>Company Name</th>
              <th>Industry</th>
              <th>Sub industry</th>
              <!-- <th>User</th> -->
              <th>Is holding</th>
              <th>Created By</th>
              <th colspan="3"><center> Actions <Center></td>
            </tr>
            </thead>
            <tbody>
            <% @companies.each do |company| %>
              <tr  class='clickable-row' data-href="<%= admin_company_path(company) %>">
                <td class="company"><%= company.cmp_name %></td>
                <td class="company"><%= company.industry %></td>
                <td class="company"><%= company.sub_industry %></td>
                <!-- <td class="company"><%#= company.user.to_s %></td> -->
                <td class="company"><%= company.created_by.cmp_name if company.created_by.present?%></td>
                <td class="quick-actions"><%= link_to 'Edit', edit_admin_company_path(company) %></td>
                <td><%= link_to 'Destroy', admin_company_path(company), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </table>
          <%= will_paginate @companies, class: "pagination bottom-pagination"%>
        </div>
      </div>
    </div>
  </div>
</section>


<script type="text/javascript">
  $(document).on('turbolinks:load', function() {
    $(".clickable-row>td.company").click(function() {
      if($(this).hasClass('quick-actions')){
      }
      else{
        window.document.location = $(this).parent().data("href");
      }
    });
  });
</script>

app/views/admin/companies/new.html.erb
<% content_for :companies_class, "active"%>
<section class="content-header">
  <h1>
    New Company
    <small>Preview</small>
  </h1>
</section>
<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Create New Company</h3>
        </div>
        <%= render 'form', company: @company, method: 'post', path: admin_companies_path %>
      </div>
    </div>
  </div>
</section>

app/views/admin/companies/show.html.erb
<% content_for :companies_class, "active"%>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div> <p id="notice"><%= notice %></p> </div>
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Company Information</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tr>
              <th>Company name:</th><td><%= @company.cmp_name %> </td>
            </tr>

            <tr>
              <th>Is holding:</th><td><%= @company.is_holding %> </td>
            </tr>

            <tr>
              <th>Parent Company Name:</th><td><%= @company.created_by.cmp_name if @company.created_by.present? %> </td>
            </tr>

            <tr>
              <th>Industry:</th><td><%= @company.industry %> </td>
            </tr>

            <tr>
              <th>Sub industry:</th><td><%= @company.sub_industry %> </td>
            </tr>

            <!-- <tr>
              <th>User:</th><td><%#= @company.user.to_s %> </td>
            </tr> -->
            <tr>
              <th>Company Logo:</th><td><%= image_tag @company.company_logo.url(:thumb) %></td>
            </tr>
          </table>
          <%= link_to 'Edit', edit_admin_company_path(@company),  class: "btn btn-primary" %>
          <%= link_to 'Back', admin_companies_path, class: "btn btn-primary" %>

          <div>
            <b>Company History</b><br>
            <% @company_histories.each do |company_history| %>
              <%= link_to company_history.year, admin_company_history_path(company_history)  %><br>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>