config/routes.rb
Rails.application.routes.draw do

  root 'users#sign_in'
  get 'users/dashboard_page'

  namespace :admin do
    resources :dashboard, only: [] do
      get :dashboard_page, on: :collection
    end
    resources :users
    resources :companies
    resources :records
    resources :company_histories, only: [:show]
    resources :services
    resources :processes
  end

  namespace :users do
    get :password_new
    post :generate_new_password_email
    resources :companies, only: [:index, :show] do
      get :change_year, on: :collection
    end
    resources :company_histories, only: [:update, :create, :new]
    resources :records, only: [:edit, :update, :create, :new] do
      get :download_pdf, on: :member
      get :record_pdf, on: :member
      get :download, on: :member
      patch :update_log, on: :collection
    end
  end

  devise_for :users, path: 'admins', :controllers => { :invitations => 'invitations', :sessions => 'sessions', :passwords => 'passwords'}

  # devise_for :admins , path: 'admins', :controllers => { :invitations => 'invitations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  #association
  attr_accessor :user_ids

  has_many :company_users
  has_many :users, through: :company_users, dependent: :destroy
  has_many :records, dependent: :destroy
  belongs_to :created_by, class_name: 'Company', foreign_key: 'parent_id', optional: true
  has_many :created_companies, class_name: 'Company', foreign_key: 'parent_id'
  has_many :company_histories, dependent: :destroy
  enum cmp_size: [:small, :large]

  #includes
  has_attached_file :company_logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :company_logo, content_type: ['image/jpeg', 'image/jpg', 'image/png']

  validates :cmp_name, presence: true
  validates :industry, presence: true
  validates :sub_industry, presence: true
  validates :user_ids, presence: true
  validates :parent_id, presence: true, if: -> {self.is_holding == true}
  validates_uniqueness_of :cmp_name

  def child_companies
    self.created_companies
  end
end

app/models/user_type.rb
class UserType < ApplicationRecord
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /admin/companies
  # GET /admin/companies.json
  def index
    @companies = Company.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /admin/companies/1
  # GET /admin/companies/1.json
  def show
    @company_histories = @company.company_histories
  end

  # GET /admin/companies/new
  def new
    @company = Company.new
  end

  # GET /admin/companies/1/edit
  def edit
  end

  # POST /admin/companies
  # POST /admin/companies.json
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      # @company.company_histories.build(user_id: params[:company][:user_id], year: Time.now().strftime("%Y"))
      if @company.save
        @company.users << User.where(id: params[:company][:user_ids])
        format.html { redirect_to admin_company_path(@company), notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/companies/1
  # PATCH/PUT /admin/companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        @company.users << User.where(id: params[:company][:user_ids])
        format.html { redirect_to admin_company_path(@company), notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/companies/1
  # DELETE /admin/companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:cmp_name, :industry, :sub_industry, :is_holding, :parent_id, :company_logo, user_ids: [] )
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @roles = Role.where.not(name: nil)
  end

  # GET /users/1/edit
  def edit
    @roles = Role.where.not(name: nil)
  end

  # POST /users
  # POST /users.json
  def create
    @roles = Role.where.not(name: nil)
    @user = User.new(user_params)
    @user.skip_password_validation = true
    @user.roles << Role.find(params[:user][:user_role]) if params[:user][:user_role].present?
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @roles = Role.where.not(name: nil)
    @user.role_ids = params[:user][:user_role]
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :user_role)
    end
end

app/controllers/users/companies_controller.rb
class Users::CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :get_companies
  before_action :set_company, only: [:show, :change_year]
  before_action :user_side


  def user_side
    if current_user.role == "Admin"
      redirect_to dashboard_page_admin_dashboard_index_path
    end
  end


  def index
    if current_user.role == 'Consultant'
      # @companies = @companies.where(user_id: current_user.id)
      @companies = @companies.includes(:users).where('users.id = ?', current_user.id).references(:users)

    end
    @companies = @companies.paginate(:page => params[:page], :per_page => 8)
  end

  def show
    if flash['year'].present?
      @working_year = flash['year']
    else
      @working_year = Time.now().strftime("%Y")
    end

    if current_user.role == "Consultant"
      @company_histories = @company_histories.where(user_id: current_user.id)
      @records = @records.where(user_id: current_user.id)
    end

    if !@company_histories.present?
      @company_history = CompanyHistory.create(user_id: current_user.id, company_id: @company.id, year: Time.now().strftime("%Y"))
      @company_histories = CompanyHistory.where(company_id: @company.id)
    end

    @company_histories_years = @company_histories.order(:year).pluck(:year)
    @records_years = @records.where.not(date_of_service_provided: nil).all.order("date_of_service_provided").map {|d| d.date_of_service_provided.strftime("%Y").to_i }.uniq
    if @records_years.any?
      @years = (@records_years + @company_histories_years).uniq.sort
    else
      @years = (@company_histories_years).uniq.sort
    end

    @current_company_history = @company_histories.find_by(year: @working_year)
  end

  def change_year
    if current_user.role == 'Consultant'
      @company_histories = @company_histories.where(user_id: current_user.id)
    end
    @current_company_history = @company_histories.find_by(year: params[:year])

    if !@current_company_history.present?
      @current_company_history = CompanyHistory.create!(user_id: @company.user_id, company_id: @company.id, year: params[:year])
    end

    respond_to do |format|
      format.js
    end
  end

  protected

  def set_company
    @company = Company.find(params[:id])
    @company_histories = @company.company_histories
    @records = @company.records.order("date_of_service_provided")
  end

  def get_companies
    @companies = Company.all
  end

end

app/controllers/users/company_histories_controller.rb
class Users::CompanyHistoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company_history, only: [:update]


  # POST /company_histories
  # POST /company_histories.json
  def create
    @company_history = CompanyHistory.new(company_id: params[:company],user_id: params[:user],year: params[:year])

    # @company_history = CompanyHistory.new(company_history_params)
    respond_to do |format|
      if @company_history.save
        format.html { redirect_to users_company_path(@company_history.company), notice: 'Company history was successfully created.' }
        format.json { render :show, status: :created, location: @company_history }
      else
        format.html {  redirect_to users_company_path(@company_history.company), notice: 'There is a problem in create.' }
        format.json { render json: @company_history.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /company_histories/1
  # PATCH/PUT /company_histories/1.json
  def update
    respond_to do |format|
      if @company_history.update(company_history_params)
        format.html { redirect_to users_company_path(@company_history.company), notice: 'Company history was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_history }
      else
        @company_history.role = current_user.role
        format.html { redirect_to users_company_path(@company_history.company), :flash => { :errors => @company_history.errors, :year => @company_history.year } }
        format.json { render json: @company_history.errors, status: :unprocessable_entity }
      end
    end
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_company_history
    @company_history = CompanyHistory.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def company_history_params
    params.require(:company_history).permit(:date_of_service_provided, :cmp_mission, :cmp_vision, :cmp_values, :cmp_value_proposition, :cmp_business_plan, :cmp_hr_provider, :cmp_competitors, :cmp_organizational_structure, :cmp_size, :number_of_workers, :work_environment_score, :workers_profile, :workers_average_age, :workers_average_time_in_company, :cmp_changes_in_last_year, :geographical_state, :geographical_region, :political_context, :economic_context, :social_context, :technological_context, :environmental_context, :legal_context, :relationship_with_client, :complexity_in_relationship_with_client, :primary_contact_name, :primary_contact_phone, :primary_contact_cellphone, :position_of_primary_contact, :primary_contact_email, :secondary_contact_name, :contact_position, :secondary_contact_email, :consultant_charge, :service_description, :service_complexities_while_offering, :score, :conditions, :last_service_provided_name, :service_start_date, :service_end_date, :user, :company, :year)
  end

end

app/controllers/users/records_controller.rb
class Users::RecordsController < ApplicationController

  before_action :set_record, only: [:edit, :update, :download_pdf, :record_pdf, :download]
  before_action :authenticate_user!

  # GET /records
  # GET /records.json
  # def index
  #   @records = Record.all
  # end

  # GET /records/1
  # GET /records/1.json
  # def show
  # end

  # GET /records/new
  def new
    @company = Company.find(params[:company])
    # @record = Record.new
    @record = @company.records.build
    @company_id = @company.id
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)
    puts @record.as_json
    puts @record.company_id
    @log = @record.logs.build(state: params[:record][:state], user_id: current_user.id) if params[:record][:state].present?
    respond_to do |format|
      if @record.save
        format.html { redirect_to users_company_path(@record.company), notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        @company_id = @record.company_id
        format.html { render :new }
        # format.html { render action: :new, company: @record.company_id }
        # format.html { render new, company: @record.company_id, json: @record.errors }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    @log = @record.logs.build(state: params[:record][:state], user_id: current_user.id) if params[:record][:state].present?
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to users_company_path(@record.company), notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        # format.html { redirect_to users_company_path(@record.company), notice: "There is a problem in update." }
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to admin_records_path, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download_pdf
    html = render_to_string(:action => :record_pdf,id: params[:id], :layout => false)
    pdf = WickedPdf.new.pdf_from_string(html)
    send_data(pdf,:filename    => "records_#{@record.id}.pdf", type: :pdf)
  end

  def record_pdf
  end

  def download
    send_file @record.record_pdf.path,
    :filename => @record.record_pdf_file_name,
    :type => @record.record_pdf_content_type,
    :disposition => 'attachment'
    flash[:notice] = "Your file has been downloaded"
  end

  def update_log
    @log = Log.find(params[:log_id]) if params[:log_id].present?
    @log.update(description: params[:description])
    respond_to do |format|
      request.format.html? ? format.html {} : format.js {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:cmp_name, :cmp_phone_number, :cmp_general_managers_name, :cmp_hrm_name, :cmp_hrm_email, :official_name_of_client, :cmp_business_plan, :chilean_id_number, :cmp_address, :cmp_state, :cmp_city, :cmp_phone, :cmp_fax, :cmp_number, :cmp_office, :bill_receiver_name, :bill_receiver_phone, :number_of_employees, :affiliates_in_city, :affiliates_in_state, :affiliates_in_country, :primary_contact_person_name, :primary_contact_person_phone, :primary_contact_person_role, :primary_contact_person_email, :date_of_service_provided, :description_of_service, :value_of_service, :service_duration, :state, :user_id, :company_id, :name, :number_of_segments, :survey_mode, :record_pdf, :service_id, :service_duration_parameter, :cmp_general_managers_email, :service_conditions, :user_role, :process_table_id)
    end

end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/users/companies_helper.rb
module Users::CompaniesHelper
end

app/helpers/users/company_histories_helper.rb
module Users::CompanyHistoriesHelper
end

app/helpers/users/records_helper.rb
module Users::RecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/companies/change_year.js.erb
$( "#hoja" ).html("<%=j render 'users/company_histories/form', company_history: @current_company_history, method: 'patch', path: users_company_history_path(@current_company_history.id) %>" );

app/views/users/companies/index.html.erb
<% content_for :users_companies_class, "active"%>

<section class="main">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-4 col-12">
        <h2> <%= current_user.to_s %><span>companies</span></h2>
      </div>
      <div class="col-lg-9 col-md-8 col-12 text-right">
        <div class="bar-right">
        </div>
      </div>
      <div class="col-12">
        <div class="timeline-bg bg-inverse">
          <div class="row">
            <% @companies.order(:cmp_name).each do |company|%>
                <div class="col-md-3 col-sm-4 col-xs-6">
                  <%= link_to users_company_path(company)  do %>
                    <div class="list-box bkg-gray">
                      <% if company.company_logo.present? %>
                        <%= image_tag company.company_logo.url(:thumb) %>
                      <% else %>
                        <img src="/assets/list-icon.png" alt="" title="" height="32" width="72" />
                      <% end %>
                      <% span_class = '' %>
                      <% if company.records.count == 0 %>
                        <%  span_class = "s-circle-red" %>
                      <% elsif (company.records.last.updated_at <= DateTime.now - 3.month)%>
                        <%  span_class = "s-circle-yellow" %>
                      <% end %>
                      <span class="s-circle <%= span_class %>"></span>
                      <div class="list-detail">
                        <p>Id: <%= company.id %> </p>
                        <p>Name: <%= company.cmp_name %> </p>
                        <p>Number of Children: <%= company.created_companies.count %> </p>
                      </div>
                    </div>
                  <%end%>
                </div>
            <% end %>
          </div>
        </div>
        <%= will_paginate @companies, class: "pagination port_pagination"%>
      </div>
    </div>
  </div>
</section>

app/views/users/companies/show.html.erb
<% content_for :company_class, "active"%>
<div> <p id="notice"><%= notice %></p> </div>

<section class="main">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-4 col-12">
        <h2><%= @company.cmp_name %> <span><%= @company.industry %></span></h2>
      </div>
      <div class="col-lg-9 col-md-8 col-12 text-right">
        <div class="bar-right">
          <div class="form-group select">
            <%= select_tag 'child_companies', options_from_collection_for_select(@company.child_companies, "id", "cmp_name"), { class: "form-control", include_blank: 'Select child company'} %>
          </div>
        </div>
      </div>
      <div class="col-12">
        <div class="timeline-bg bg-inverse">
          <div class="timeline-top">
            <ul class="nav nav-tabs" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#comercial">Comercial</a>
              </li>
              <li class="nav-item">
                <a class="nav-link hoja" data-toggle="tab" href="#hoja" >Hoja de Vida</a>
              </li>
            </ul>
            <div class="year-slide">
              <div class="owl-carousel owl-theme">
                <% @years.each do |year|%>
                  <div class="item"><a href="scroll_<%=year%>" data="<%= year %>" class="year"><%= year %></a></div>
                <% end %>
              </div>
            </div>
            <%= link_to "Next", users_company_histories_path(user: current_user.id, company: @current_company_history.company ,year: @years.last.to_i + 1), class: "add-year",  :method => :post %>
            <%= link_to new_users_record_path(company: @company.id), class: "create-new-btn" do %>
              <button type="button" class="btn btn-primary ">Create New record</button>
            <% end %>
          </div>
      <div class="tab-content">
            <div id="comercial" class="tab-pane active">
              <div class="timeline-wrap">
                <div class="row">
                  <div class="col-lg-10 offset-lg-1 col-12">
                    <% @years.reverse.each do |year| %>
                      <div class="title-bar text-center" id="<%= year %>-scroll">
                        <span id="scroll_<%=year%>" ><%= year %></span>
                      </div>
                      <ul class="timeline">
                        <% @records.where('extract(year from date_of_service_provided) IN(?)', year).reverse.each_with_index do |record, index| %>
                          <li class="<%= index % 2 == 0 ? '' : 'timeline-inverted'%>">
                            <div class="card <%= record.state == 'created' ? 'bg-blue' : record.state ==
                          'signed' ? 'bg-green' : record.state == 'valued' ? 'bg-gray' : record.state == 'approved' ? 'bg-yellow' : '' %>"> <%= record.id %>
                              <h5><%= I18n.t("date.month_names")[record.created_at.month] %> <%= year %></h5>
                              <ul>
                                <li><%= record.date_of_service_provided %></li>
                                <li><i class="fa fa-calendar-alt"></i><%= record.service_duration %></li>
                                <li><i class="fa fa-dollar-sign"></i><%= record.number_of_segments %> segments</li>
                                <li><i class="fa fa-dollar-sign"></i><%= record.value_of_service %>  UF (Price)</li>
                              </ul>
                              <div class="right">
                                <span><%= record.company.company_histories.last.work_environment_score %></span>
                                (Trust Index Score)<br>goes to ranking
                              </div>
                              <%= link_to edit_users_record_path(record) do %>
                                <button type="button" class="btn btn-primary">Edit</button>
                              <% end %>
                            </div>
                          </li>
                        <% end %>
                        <li class="clearfix" style="float: none;"></li>
                      </ul>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>

            <div id="hoja" class="tab-pane">
              <%= render 'users/company_histories/form', company_history: @current_company_history, method: 'patch', path: users_company_history_path(@current_company_history.id) %>
            </div>

          </div>

        </div>
      </div>
    </div>
  </div>
</section>


<script>
  $( document ).ready(function() {
    var year = '<%= flash['year'] %>';
    if(year != '')
    {
      $('.hoja').click();
    }

    $('#<%= @working_year %>-id').addClass('active');

    $('#create-new-record').click(function() {
      var selected_year = $('ul.ul-year').find('a.active').text();
      var company_id = '<%= @current_company_history.company.id %>';
      var user_id = '<%= current_user.id %>';
      $.ajax({
        url: '<%= users_records_path %>',
        type: 'post',
        data: {"company": company_id,'user': user_id}
      });

    });


    $('.year').click(function(e) {
      e.preventDefault();
      '<% @years.each do |year|%>'
        if ('<%= year.to_s %>' == e.target.text)
        {
            $('#<%= year %>-id').addClass('active');
            $('html, body').animate({
                  scrollTop: $("#<%= year %>-scroll").offset().top
              }, 2000);
        }
        else
        {
          $('#<%= year %>-id').removeClass('active');
        }
      '<% end %>'
      var year = e.target.text;
      var company_id = '<%= @current_company_history.company.id %>'
      $.ajax({
        url: '<%= change_year_users_companies_path %>',
        type: 'GET',
        data: {"id": company_id, "year": year}
      });
    })

  });
</script>

<script>
    $(function(){
      $('#child_companies').bind('change', function () {
         var url = "/users/companies/" + $(this).val()
          if (url) {
              window.location.replace(url);
          }
          return false;
      });
    });
</script>

<script type="text/javascript">
  $('.owl-carousel').owlCarousel({
    loop:false,
    items: 5,
    nav:true
  })
</script>