config/routes.rb
Rails.application.routes.draw do

  root 'users#sign_in'
  get 'users/dashboard_page'

  namespace :admin do
    resources :dashboard, only: [] do
      get :dashboard_page, on: :collection
    end
    resources :users
    resources :companies
    resources :records
    resources :company_histories, only: [:show]
    resources :services
    resources :processes
  end

  namespace :users do
    get :password_new
    post :generate_new_password_email
    resources :companies, only: [:index, :show] do
      get :change_year, on: :collection
    end
    resources :company_histories, only: [:update, :create, :new]
    resources :records, only: [:edit, :update, :create, :new] do
      get :download_pdf, on: :member
      get :record_pdf, on: :member
      get :download, on: :member
      patch :update_log, on: :collection
    end
  end

  devise_for :users, path: 'admins', :controllers => { :invitations => 'invitations', :sessions => 'sessions', :passwords => 'passwords'}

  # devise_for :admins , path: 'admins', :controllers => { :invitations => 'invitations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_type.rb
class UserType < ApplicationRecord
end

app/controllers/admin/records_controller.rb
class Admin::RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /records
  # GET /records.json
  def index
    @records = Record.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to admin_record_path(@record), notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to admin_record_path(@record), notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to admin_records_path, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:cmp_name, :cmp_phone_number, :cmp_general_managers_name, :cmp_hrm_name, :cmp_hrm_email, :official_name_of_client, :cmp_business_plan, :chilean_id_number, :cmp_address, :cmp_state, :cmp_city, :cmp_phone, :cmp_fax, :cmp_number, :cmp_office, :bill_receiver_name, :bill_receiver_phone, :number_of_employees, :affiliates_in_city, :affiliates_in_state, :affiliates_in_country, :primary_contact_person_name, :primary_contact_person_phone, :primary_contact_person_role, :primary_contact_person_email, :date_of_service_provided, :description_of_service, :value_of_service, :service_duration, :state, :user_id, :company_id, :number_of_segments, :survey_mode, :service_id, :service_duration_parameter, :user_role, :cmp_general_managers_email,  :service_conditions, :process_table_id)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @roles = Role.where.not(name: nil)
  end

  # GET /users/1/edit
  def edit
    @roles = Role.where.not(name: nil)
  end

  # POST /users
  # POST /users.json
  def create
    @roles = Role.where.not(name: nil)
    @user = User.new(user_params)
    @user.skip_password_validation = true
    @user.roles << Role.find(params[:user][:user_role]) if params[:user][:user_role].present?
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @roles = Role.where.not(name: nil)
    @user.role_ids = params[:user][:user_role]
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :user_role)
    end
end

app/controllers/users/companies_controller.rb
class Users::CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :get_companies
  before_action :set_company, only: [:show, :change_year]
  before_action :user_side


  def user_side
    if current_user.role == "Admin"
      redirect_to dashboard_page_admin_dashboard_index_path
    end
  end


  def index
    if current_user.role == 'Consultant'
      # @companies = @companies.where(user_id: current_user.id)
      @companies = @companies.includes(:users).where('users.id = ?', current_user.id).references(:users)

    end
    @companies = @companies.paginate(:page => params[:page], :per_page => 8)
  end

  def show
    if flash['year'].present?
      @working_year = flash['year']
    else
      @working_year = Time.now().strftime("%Y")
    end

    if current_user.role == "Consultant"
      @company_histories = @company_histories.where(user_id: current_user.id)
      @records = @records.where(user_id: current_user.id)
    end

    if !@company_histories.present?
      @company_history = CompanyHistory.create(user_id: current_user.id, company_id: @company.id, year: Time.now().strftime("%Y"))
      @company_histories = CompanyHistory.where(company_id: @company.id)
    end

    @company_histories_years = @company_histories.order(:year).pluck(:year)
    @records_years = @records.where.not(date_of_service_provided: nil).all.order("date_of_service_provided").map {|d| d.date_of_service_provided.strftime("%Y").to_i }.uniq
    if @records_years.any?
      @years = (@records_years + @company_histories_years).uniq.sort
    else
      @years = (@company_histories_years).uniq.sort
    end

    @current_company_history = @company_histories.find_by(year: @working_year)
  end

  def change_year
    if current_user.role == 'Consultant'
      @company_histories = @company_histories.where(user_id: current_user.id)
    end
    @current_company_history = @company_histories.find_by(year: params[:year])

    if !@current_company_history.present?
      @current_company_history = CompanyHistory.create!(user_id: @company.user_id, company_id: @company.id, year: params[:year])
    end

    respond_to do |format|
      format.js
    end
  end

  protected

  def set_company
    @company = Company.find(params[:id])
    @company_histories = @company.company_histories
    @records = @company.records.order("date_of_service_provided")
  end

  def get_companies
    @companies = Company.all
  end

end

app/controllers/users/company_histories_controller.rb
class Users::CompanyHistoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company_history, only: [:update]


  # POST /company_histories
  # POST /company_histories.json
  def create
    @company_history = CompanyHistory.new(company_id: params[:company],user_id: params[:user],year: params[:year])

    # @company_history = CompanyHistory.new(company_history_params)
    respond_to do |format|
      if @company_history.save
        format.html { redirect_to users_company_path(@company_history.company), notice: 'Company history was successfully created.' }
        format.json { render :show, status: :created, location: @company_history }
      else
        format.html {  redirect_to users_company_path(@company_history.company), notice: 'There is a problem in create.' }
        format.json { render json: @company_history.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /company_histories/1
  # PATCH/PUT /company_histories/1.json
  def update
    respond_to do |format|
      if @company_history.update(company_history_params)
        format.html { redirect_to users_company_path(@company_history.company), notice: 'Company history was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_history }
      else
        @company_history.role = current_user.role
        format.html { redirect_to users_company_path(@company_history.company), :flash => { :errors => @company_history.errors, :year => @company_history.year } }
        format.json { render json: @company_history.errors, status: :unprocessable_entity }
      end
    end
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_company_history
    @company_history = CompanyHistory.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def company_history_params
    params.require(:company_history).permit(:date_of_service_provided, :cmp_mission, :cmp_vision, :cmp_values, :cmp_value_proposition, :cmp_business_plan, :cmp_hr_provider, :cmp_competitors, :cmp_organizational_structure, :cmp_size, :number_of_workers, :work_environment_score, :workers_profile, :workers_average_age, :workers_average_time_in_company, :cmp_changes_in_last_year, :geographical_state, :geographical_region, :political_context, :economic_context, :social_context, :technological_context, :environmental_context, :legal_context, :relationship_with_client, :complexity_in_relationship_with_client, :primary_contact_name, :primary_contact_phone, :primary_contact_cellphone, :position_of_primary_contact, :primary_contact_email, :secondary_contact_name, :contact_position, :secondary_contact_email, :consultant_charge, :service_description, :service_complexities_while_offering, :score, :conditions, :last_service_provided_name, :service_start_date, :service_end_date, :user, :company, :year)
  end

end

app/controllers/users/records_controller.rb
class Users::RecordsController < ApplicationController

  before_action :set_record, only: [:edit, :update, :download_pdf, :record_pdf, :download]
  before_action :authenticate_user!

  # GET /records
  # GET /records.json
  # def index
  #   @records = Record.all
  # end

  # GET /records/1
  # GET /records/1.json
  # def show
  # end

  # GET /records/new
  def new
    @company = Company.find(params[:company])
    # @record = Record.new
    @record = @company.records.build
    @company_id = @company.id
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)
    puts @record.as_json
    puts @record.company_id
    @log = @record.logs.build(state: params[:record][:state], user_id: current_user.id) if params[:record][:state].present?
    respond_to do |format|
      if @record.save
        format.html { redirect_to users_company_path(@record.company), notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        @company_id = @record.company_id
        format.html { render :new }
        # format.html { render action: :new, company: @record.company_id }
        # format.html { render new, company: @record.company_id, json: @record.errors }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    @log = @record.logs.build(state: params[:record][:state], user_id: current_user.id) if params[:record][:state].present?
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to users_company_path(@record.company), notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        # format.html { redirect_to users_company_path(@record.company), notice: "There is a problem in update." }
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to admin_records_path, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download_pdf
    html = render_to_string(:action => :record_pdf,id: params[:id], :layout => false)
    pdf = WickedPdf.new.pdf_from_string(html)
    send_data(pdf,:filename    => "records_#{@record.id}.pdf", type: :pdf)
  end

  def record_pdf
  end

  def download
    send_file @record.record_pdf.path,
    :filename => @record.record_pdf_file_name,
    :type => @record.record_pdf_content_type,
    :disposition => 'attachment'
    flash[:notice] = "Your file has been downloaded"
  end

  def update_log
    @log = Log.find(params[:log_id]) if params[:log_id].present?
    @log.update(description: params[:description])
    respond_to do |format|
      request.format.html? ? format.html {} : format.js {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:cmp_name, :cmp_phone_number, :cmp_general_managers_name, :cmp_hrm_name, :cmp_hrm_email, :official_name_of_client, :cmp_business_plan, :chilean_id_number, :cmp_address, :cmp_state, :cmp_city, :cmp_phone, :cmp_fax, :cmp_number, :cmp_office, :bill_receiver_name, :bill_receiver_phone, :number_of_employees, :affiliates_in_city, :affiliates_in_state, :affiliates_in_country, :primary_contact_person_name, :primary_contact_person_phone, :primary_contact_person_role, :primary_contact_person_email, :date_of_service_provided, :description_of_service, :value_of_service, :service_duration, :state, :user_id, :company_id, :name, :number_of_segments, :survey_mode, :record_pdf, :service_id, :service_duration_parameter, :cmp_general_managers_email, :service_conditions, :user_role, :process_table_id)
    end

end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/users/companies_helper.rb
module Users::CompaniesHelper
end

app/helpers/users/company_histories_helper.rb
module Users::CompanyHistoriesHelper
end

app/helpers/users/records_helper.rb
module Users::RecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/records/_form.html.erb
<div> <p id="notice"><%= notice %></p> </div>
<div class="timeline-bg bg-inverse">
  <%= form_for record, class: "record_detail", url: path, method: method do |form| %>
  <div class="row">
    <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
        
        <%= render 'users/records/record_detail', form: form, record: record %>

    </div>

    <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
      <div class="info-log">
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#home">Service Info</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#menu1">Log</a>
          </li>
        </ul>
        <div class="tab-content">
          <div id="home" class="container tab-pane active"><br>
            <%= form.hidden_field :user_role, value: current_user.role %>
            <%= render 'users/records/service_detail', form: form, record: record %>
          </div>
          <div id="menu1" class="container tab-pane"><br>
            <table class="table">
              <thead>
                <tr>
                  <th>State</th>
                  <th>User</th>
                  <th>Description</th>
                  <th>Submit</th>
                </tr>
              </thead>
              <tbody>
                <% @record.logs.each do |log| %>
                  <tr>
                    <td><%= log.state %></td>
                    <td><%= log.user.to_s %></td>
                    <td>
                      <div class="form-group record_detail">
                        <%= text_area_tag :description, log.description, class: 'form-control', id: "description_#{log.id}" %>
                      </div>
                    </td>
                    <td>
                      <button type="button" class="btn btn-primary save" id="update_log_<%=log.id%>" data-log_id= "<%=log.id%>" >Update</button>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <!-- <div class="form-group record_detail">
              <label for="comment">Comment:</label>
              <textarea class="form-control" rows="5" id="comment"></textarea>
            </div> -->
            <!-- <div class="text-right">
              <button type="button" class="btn btn-primary save">SAVE</button>
            </div> -->
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="text-right m-t-10 text-center">
    <% unless record.state.present? %>
      <%= form.hidden_field :state, value: 'created' %>
      <%= form.submit "Created", class: "btn btn-primary"%>
      <button type="button" class= "btn btn-primary" disabled= "true" >Valued</button>
      <button type="button" class= "btn btn-primary" disabled= "true" >Approved</button>
    <% end %>

    <% if record.state.present? && current_user.role == 'Consultant' %>
      <%= form.submit "Edit", class: "btn btn-primary edit_button" if record.persisted?  %>
      <%= form.hidden_field :state, value: 'created' %>
      <%= form.submit "Created", class: "btn btn-primary"%>
      <button type="button" class= "btn btn-primary" disabled= "true" >Valued</button>
      <button type="button" class= "btn btn-primary" disabled= "true" >Approved</button>
    <% end %>

    <% if record.state.present? %>
      <% if record.state == "valued" && current_user.role == 'Leader' %>
        <%= form.hidden_field :state, value: 'approved', class: "hidden_field" %>
        <%= form.submit "Edit", class: "btn btn-primary edit_button" %>
        <button type="button" class= "btn btn-primary" disabled= "true" >Created</button>
        <button type="button" class= "btn btn-primary" disabled= "true" >Valued</button>
        <%= form.submit "Approved", class: "btn btn-primary" %>
      <% elsif record.state == "created" && current_user.role == 'Leader' %>
        <%= form.hidden_field :state, value: 'valued', class: "hidden_field" %>
        <%= form.submit "Edit", class: "btn btn-primary edit_button"%>
        <button type="button" class= "btn btn-primary" disabled= "true" >Created</button>
        <%= form.submit "Valued", class: "btn btn-primary"%>
        <button type="button" class= "btn btn-primary" disabled= "true" >Approved</button>
      <% end %>
    <% end %>
    <% if record.state.present? && record.state == "approved"%>
      <h2>The record has been approved </h2>
    <% end %>
  </div>
  <% end %>
</div>

<script type="text/javascript">
  $(document).on('turbolinks:load', function() {
    $(".edit_button").click(function(){
      $(".hidden_field").remove()
    });

    $('button[id^="update_log_"]').click(function(){
      var log_id = $(this).data("log_id");
      var description = $("#description_" + log_id).val();
      $.ajax({
        url: '<%= update_log_users_records_path %>',
        type: 'patch',
        data: {"description": description, 'log_id': log_id}
      });
    })

  })
</script>

app/views/users/records/_service_detail.html.erb
<%= form.label :date_of_service_provided %>
  <div class=" form-inline form-group">
    <div class="general-dates">
      <%= form.date_select :date_of_service_provided, {}, class: 'form-control small-field service-date' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :service_id, "Select service" %>
    <%= form.select :service_id, Service.all.map{|r| [r.name, r.id]}, {}, { class: 'form-control select2', style: "width: 100%;"}  %>
  </div>

  <div class="form-group">
    <%= form.label :process_table_id, "Select service" %>
    <%= form.select :process_table_id, ProcessTable.all.map{|r| [r.name, r.id]}, {}, { class: 'form-control select2', style: "width: 100%;"}  %>
  </div>

  <div class="form-group medicon-class">
    <%= form.label :number_of_segments %>
    <%= form.number_field :number_of_segments, class: 'form-control small-field', placeholder: "Enter number of segments" %>
    <p class='error'><%= show_errors(record, :number_of_segments, "Number of Segments") %></p>
  </div>

  <div class="form-group medicon-class">
    <%= form.label :survey_mode %>
    <%= form.select :survey_mode, Record.survey_modes.keys.map{|r| [r.titleize, r]}, {}, { class: 'form-control small-field select2', style: "width: 100%;"}   %>
  </div>

  <div class="form-group">
    <%= form.label :service_duration_parameter %>
    <%= form.select :service_duration_parameter, Record.service_duration_parameters.keys.map{|r| [r.titleize, r]},{}, { class: 'form-control select2', style: "width: 100%;"}  %>
  </div>
  <div class="form-group">
    <%= form.label :service_duration %>
    <%= form.select :service_duration, options_for_select(Record::DAYS), {}, class: 'form-control select2', placeholder: "Enter service duration" %>
  </div>

  <div class="form-group">
    <%= form.label :value_of_service %>
    <% if current_user.role == 'Leader' %>
      <%= form.text_field :value_of_service, class: 'form-control small-field', placeholder: "Enter value of service" %>
    <% else %>
      <%= form.text_field :value_of_service, class: 'form-control small-field', placeholder: "Enter value of service", disabled: :true %>
    <%end%>
    <p class='error'><%= show_errors(record, :value_of_service, "Value of Service") %></p>
  </div>

app/views/users/records/edit.html.erb
<section class="main">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-4 col-12">
        <% if  @record.record_pdf.present? %>
          <h2>
            Record Id= <%= @record.id %>
            <%= link_to download_users_record_path, target: "_blank" do %>
              <i class="fas fa-file-pdf" style="font-size:25px; margin-left: 15px;"></i>
            <% end %>
          </h2>

        <% else %>
          <h2>
            Record Id= <%= @record.id %> <%= link_to download_pdf_users_record_path, target: "_blank"  do %>
               <i class="fas fa-file-pdf" style="font-size:25px; margin-left: 15px;"></i>
              <%end%>
          </h2>
        <% end %>

      </div>
      <div class="col-lg-9 col-md-8 col-12 text-right">
        <div class="bar-right">
          <div class="form-group">
            <%=link_to users_company_path(@record.company) do %>
              <button type="button" class="btn btn-primary">Back to Company</button>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-12 record-edit">
        <%= render 'users/records/form', record: @record, method: 'patch', path: users_record_path() %>
    </div>
  </div>
</div>
</section>

app/views/users/records/new.html.erb
<section class="main">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-4 col-12">
        <h2>New Record</h2>
      </div>
      <div class="col-lg-9 col-md-8 col-12 text-right">
        <div class="bar-right">
          <div class="form-group">
            <%=link_to users_companies_path do %>
              <button type="button" class="btn btn-primary">Back </button>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-12 record-edit">
        <%= render 'users/records/form', record: @record, method: 'post', path: users_records_path %>
    </div>
  </div>
</div>
</section>

app/views/users/records/update_log.js.erb
$("#description_<%= params[:log_id] %>").val("<%= params[:description]%>");
document.getElementById("notice").innerHTML = "Log has been updated successfully";